package UI;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 * @program: ProcessControl03
 * @description:
 * @author: GYF
 * @create: 2020-12-10 20:37
 */
public class UI {
    private JPanel panel1;
    private JButton 添加Button;
    private JButton 执行Button;
    private JButton 暂停Button;
    private JButton 时间片运行Button;
    private JButton 停止Button;
    private JTextArea TextArea1;
    private JTextArea TextArea3;
    private JTextArea TextArea4;
    private JTextArea TextArea5;
    private JTextArea TextArea6;
    private JTextField textField2;
    private JButton Button6;
    private JTextField textField3;
    private JButton Button7;
    private JButton Button8;
    private JTextArea textArea2;
    private JTextArea bbbbbbbbbbbbTextArea;
    public JTextField textField1;

    public UI() {
        添加Button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("UI");
        frame.setContentPane(new UI().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.NORTH);
        添加Button = new JButton();
        添加Button.setText("添加");
        panel2.add(添加Button);
        执行Button = new JButton();
        执行Button.setText("执行");
        panel2.add(执行Button);
        暂停Button = new JButton();
        暂停Button.setText("暂停");
        panel2.add(暂停Button);
        时间片运行Button = new JButton();
        时间片运行Button.setText("时间片运行");
        panel2.add(时间片运行Button);
        停止Button = new JButton();
        停止Button.setText("停止");
        panel2.add(停止Button);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:d:grow"));
        panel1.add(panel3, BorderLayout.CENTER);
        TextArea3 = new JTextArea();
        TextArea3.setEditable(false);
        TextArea3.setLineWrap(true);
        TextArea3.setText("cccccccccccc");
        TextArea3.setToolTipText("");
        CellConstraints cc = new CellConstraints();
        panel3.add(TextArea3, cc.xy(5, 1, CellConstraints.FILL, CellConstraints.FILL));
        TextArea4 = new JTextArea();
        TextArea4.setEditable(false);
        TextArea4.setLineWrap(true);
        TextArea4.setText("dddddddddddd");
        panel3.add(TextArea4, cc.xy(7, 1, CellConstraints.FILL, CellConstraints.FILL));
        TextArea5 = new JTextArea();
        TextArea5.setEditable(false);
        TextArea5.setLineWrap(true);
        TextArea5.setText("eeeeeeeeeeee");
        panel3.add(TextArea5, cc.xy(9, 1, CellConstraints.FILL, CellConstraints.FILL));
        TextArea6 = new JTextArea();
        TextArea6.setEditable(false);
        TextArea6.setLineWrap(true);
        TextArea6.setText("ffffffffffff");
        panel3.add(TextArea6, cc.xy(11, 1, CellConstraints.FILL, CellConstraints.FILL));
        TextArea1 = new JTextArea();
        TextArea1.setEditable(false);
        TextArea1.setEnabled(true);
        TextArea1.setLineWrap(true);
        TextArea1.setText("aaaaaaaaaaaa");
        panel3.add(TextArea1, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        bbbbbbbbbbbbTextArea = new JTextArea();
        bbbbbbbbbbbbTextArea.setEditable(false);
        bbbbbbbbbbbbTextArea.setText("bbbbbbbbbbbb");
        panel3.add(bbbbbbbbbbbbTextArea, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.FILL));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:d:grow,top:4dlu:noGrow,center:d:noGrow"));
        panel1.add(panel4, BorderLayout.SOUTH);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow"));
        panel4.add(panel5, cc.xywh(3, 1, 1, 3));
        textField2 = new JTextField();
        panel5.add(textField2, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        Button6 = new JButton();
        Button6.setText("中断");
        panel5.add(Button6, cc.xy(3, 3));
        textField3 = new JTextField();
        panel5.add(textField3, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        Button7 = new JButton();
        Button7.setText("阻塞");
        panel5.add(Button7, cc.xy(3, 5));
        Button8 = new JButton();
        Button8.setText("唤醒");
        panel5.add(Button8, cc.xy(3, 7));
        textField1 = new JTextField();
        panel5.add(textField1, cc.xy(1, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        textArea2 = new JTextArea();
        textArea2.setEditable(false);
        textArea2.setText("");
        panel4.add(textArea2, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
